title: RPGX
description: Jueguitos porno y no tan porno.
author: RPGX
github: https://github.com/agusmakmun
about: Minisitio con los parches de jueguitos que traduzco.
disqus_shortname: anime-gx
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://fb.com/AnimeGX"
    - icon: fa-twitter
      link: "https://twitter.com/GX_SyL"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Acerca de
      url: /about/
    - text: Proyectos
      url: /projects/
    - text: RSS
      url: /feed.xml

url: "http://rpgx.animegx.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
